Added two games from WiVe
flutter-belgium/made_in_flutter_belgium_data pull request #82
Opened 2023-07-24 12:37 UTC by ikbendewilliam

2023-08-01 11:55 UTC, vanlooverenkoen requested changes

2023-08-01 11:55 UTC, vanlooverenkoen commented on projects/Neon wars/assets/img/screenshots/screenshot_1.webp
This 3168x1440 size image is quite large. try to make it smaller to match the other image sized

2023-08-01 11:55 UTC, vanlooverenkoen commented on projects/Cycling Escape/assets/img/app_icon.webp
the logo is quite pixelated, do you have a better version of this app icon?

2023-08-01 20:31 UTC, ikbendewilliam commented on projects/Cycling Escape/assets/img/app_icon.webp
No 😂 the logo is that pixelated

2023-08-03 09:22 UTC, vanlooverenkoen approved these changes

2023-08-03 09:22 UTC, merged